### PR TITLE
Move to fixed size array for metadata

### LINKED ISSUE #9: Move to fixed-size array
Currently using tuples for geometry metadata. Apparently, this is not the correct way to deal with objects in rust and a fixed size array is preferable.

### PR DESCRIPTION
**Pull request by lweitkamp**
NB: this also changes the direction dtype from unsigned integers to fp64 (more fitting).

### CODE REVIEW

File: src/image/image.rs [hunk 1]
```diff
@@ -9,9 +9,9 @@ pub struct Image<T> {
     pub width:  u32,
     pub height: u32,
     pub depth:  u32,
-    pub spacing: (f64, f64, f64),
-    pub origin:  (f64, f64, f64),
-    pub direction: (u8, u8, u8, u8, u8, u8, u8, u8, u8),
+    pub spacing: [f64; 3],
```
Comment (micts) [inline src/image/image.rs:12]: So this now doesn't allow it to grow (i.e. fixed-size) and it is still immutable (by default), right?

**Review by micts — APPROVED** [review]
One clarification question, other than that looks good

File: src/image/image.rs (hunk 1 above)
Comment (lweitkamp) [reply src/image/image.rs:12]: Length is fixed to 3 and it's not `pub mut spacing` so I think yeah, its immutable in both senses.
